### ISSUE TITLE
Horizontal rules in Markdown (`---`) lead to invalid JSX

### ISSUE THREAD

**Issue by squidfunk** [michael-klein/htmdx#6]
> Sorry for opening so many issues and PRs - I'm actively using your library, so I report the errors that I encounter 😜

The following Markdown:

```` markdown
# H1
---
# H2
````

... should translate to the following HTML:

``` html
<h1>H1</h1>
<hr />
<h2>H2</h2>
```

However, as Marked seems to omit the slash on self-closing tags by default, it get's converted to:

``` html
<h1>H1</h1>
<hr>
<h2>H2</h2>
```

`htm` takes this input, cuts of everything before the `<hr>` and returns:

``` html
hr<h2>H2</h2>
```

Setting `xhtml: true` for Marked via `configureMarked` solves the problem. Maybe we should add a note on this to the README and provide `xhtml: true` as a default to Marked?

**Comment by michael-klein** [comment]
Makes sense to me, yes!

**Comment by michael-klein** [comment]
Done and published!
