### ISSUE TITLE
< and > in code blocks are parsed as tags/components

### ISSUE THREAD

**Issue by squidfunk** [michael-klein/htmdx#7]
I just realized that when a code block contains `<` or `>` characters, it is parsed as a tag, probably by `htm`.

A reproducible case:

``` ts
import { h } from "preact"
import { htmdx } from "htmdx"

const markdown = `
\`\`\` json
{
  ...,
  "authors": [
    "John Doe <john.doe@example.com>"
  ],
  ...
}
\`\`\``

console.dir(htmdx(data, h), { depth: null })
```

Yields:

``` js
[ 'pre',
  { type: 'code',
    props:
     { className: 'language-json',
       children:
        [ '{\n  ...,\n  "authors": [\n    "John Doe ',
          { type: 'john.doe@example.com',
            props: { children: '"\n  ],\n  ...\n}' },
            key: null,
            ref: null,
            __k: null,
            __: null,
            __b: 0,
            __e: null,
            __d: null,
            __c: null,
            constructor: undefined } ] },
    key: undefined,
    ref: undefined,
    __k: null,
    __: null,
    __b: 0,
    __e: null,
    __d: null,
    __c: null,
    constructor: undefined } ]
```

The type of the node is `john.doe@example.com`. Furthermore, the `pre` is messed up.

**Comment by squidfunk** [comment]
Interestingly, `marked` seems to do the right thing.

When I step through the code:

https://github.com/michael-klein/htmdx/blob/371fa6027ab595b717086197475942e8236d2b04/src/index.ts#L42

`m` contains:

```
<pre><code class="language-json">{
  ...,
  &quot;authors&quot;: [
    &quot;John Doe &lt;john.doe@example.com&gt;&quot;
  ],
  ...
}</code></pre>
```

At the end of `decodeHTML`, `m` contains:

```
<pre><code class="language-json">{
  ...,
  "authors": [
    "John Doe <john.doe@example.com>"
  ],
  ...
}</code></pre>
```

The escaping has been undone. What's the reason why you decode HTML entities anyway? Why not just leave them as-is?

**Comment by michael-klein** [comment]
Thanks for your report! The issue was that the decoding itself was in fact broken (the regex). I pushed a fix and published it to npm :)
